apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: config-setup
  namespace: inversiones1-cluster
spec:
  targetNamespace: inversiones1-cluster
  interval: 1h
  retryInterval: 3m
  timeout: 5m
  prune: true
  wait: true
  path: ./config/kubernetes/spokes/.config
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  postBuild:
    substitute:
      SPOKE_NS: inversiones1-cluster
      GIT_URL: https://github.com/lima-demos-days/Inversiones1-Businessflow
      GIT_REF: main
      FLUX_PATH: infra/gitops
