apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: spoke-management
  namespace: inversion3-cluster
spec:
  interval: 1h
  retryInterval: 3m
  timeout: 5m
  prune: true
  wait: true
  path: ./config/kubernetes/spokes/.businessflow-repo
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  postBuild:
    substitute:
      SPOKE_NS: inversion3-cluster
      GIT_URL: https://github.com/lima-demos-days/Inversion3-Businessflow
      GIT_REF: main
      FLUX_PATH: infra/gitops
